# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FRIENDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('birth', models.DateTimeField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('home', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
