# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0002_auto_20180620_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='pone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
